ignore:
  - "Mini Model <minimodel@metamodel.me>"
  - "Scrutinizer Auto-Fixer <auto-fixer@scrutinizer-ci.com>"

exclude:
  languages

mapping:
  Andreas Isaak <info@andreas-isaak.de>: Andreas Isaak <andy.jared@googlemail.com>
  Stefan Heimes <stefan_heimes@hotmail.com>: Stefan heimes <stefan_heimes@hotmail.com>
  Christopher Boelter <christopher@boelter.eu>: cboelter <christopher@boelter.eu>
